# Generated by Django 5.2.4 on 2025-08-06 04:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0002_remove_vehicle_assigned_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('interaction_type', models.CharField(max_length=50)),
                ('distance_meters', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_a_interactions', to='vehicles.vehicle')),
                ('vehicle_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_b_interactions', to='vehicles.vehicle')),
            ],
        ),
    ]
