# Generated by Django 5.2.4 on 2025-08-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='assigned_user',
        ),
    ]
